apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  happy-compute-ingress
  namespace: default
  annotations:
   cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
   - hosts:
       - neko.happycloudcomputing.com
     secretName: happy-tls-secret
  rules:
  - host: activepc.happycloudcomputing.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: active-pieces-activepieces
            port:
              number: 80

  - host: flame.happycloudcomputing.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: charts-testing-01-flame
            port:
              number: 10291

  - host: llama.happycloudcomputing.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: charts-testing-01-llama-webui
            port:
              number: 8080

  - host: gitea.happycloudcomputing.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: charts-testing-01-gitea-http
            port:
              number: 3000

  - host: codeserver.happycloudcomputing.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: charts-testing-01-code-server
            port:
              number: 8443

  - host: etherpad.happycloudcomputing.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: charts-testing-01-etherpad
            port:
              number: 9001

  - host: neko.happycloudcomputing.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: neko
            port:
              number: 10294
