apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  happy-compute-ingress
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: sample-1.ardevops.life
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: active-pieces-activepieces
            port:
              number: 80

  - host: sample-2.ardevops.life
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: charts-testing-01-flame
            port:
              number: 10291
